#!/usr/bin/env node
/*
 * gate.mjs — deterministic plumbing for the understanding gate (increment 2).
 *
 * The GRADING JUDGMENT (deriving correct answers from the diff, judging free-text) is done by the
 * agent following understanding-gate/SKILL.md via an independent grader subagent. This script only
 * does the tamper-evident bookkeeping the agent cannot fake by prose:
 *
 *   attempt  record a (pre-feedback) attempt score; returns the FIRST-attempt score for the slug
 *   mint     on a genuine pass, mint a pass token + write .understanding/passes/<slug>.json
 *   verify   recompute the token from re-derived correct answers → authentic vs forged
 *   check    fast existence + freshness check for a slug or a range (used by the pre-push hook)
 *
 * The pass TOKEN binds the range identity, the gitignored per-run nonces, the CORRECT MCQ answers,
 * and a hash of the submitted free-text answers:
 *   token = sha256(rangeSha \n sortedNonceValues \n canonicalMcqAnswers \n freeAnswersSha)
 * You cannot compute it by reading committed files: the nonces are gitignored and the correct
 * answers are nowhere on disk — you must actually know them (i.e. understand the diff). A tampered
 * pass record (token, mcq, or free-text hash) is DETECTED by `verify`.
 *
 * Exit codes:  0 ok · 1 validation error · 2 file/IO/resolver error · 3 authenticity check failed
 * Node built-ins only; framework-agnostic.
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const RESOLVER = path.join(__dirname, "..", "..", "explain-diff", "scripts", "resolve_range.sh");

function arg(name, def) { const i = process.argv.indexOf(name); return i >= 0 && process.argv[i + 1] !== undefined ? process.argv[i + 1] : def; }
function die(msg, code = 1) { console.error("gate: " + msg); process.exit(code); }
const sha256 = (s) => crypto.createHash("sha256").update(s).digest("hex");

// slug is always machine-generated by resolve_range.sh: 7hex-7hex or 7hex-7hex-6hex.
// Validate strictly — this is the security boundary against path traversal via --slug.
const SLUG_RE = /^[0-9a-f]{7}-[0-9a-f]{7}(-[0-9a-f]{6})?$/;
function assertSlug(s) { if (!s || !SLUG_RE.test(s)) die(`invalid slug '${s || ""}' (expected NNNNNNN-NNNNNNN[-NNNNNN] hex from resolve_range.sh)`); return s; }

const MAX_Q = 1000;
function intArg(name, { min = 0, max = MAX_Q } = {}) {
  const raw = arg(name);
  if (raw === undefined) die(`missing ${name}`);
  if (!/^-?\d+$/.test(String(raw))) die(`${name} must be an integer, got '${raw}'`);
  const n = parseInt(raw, 10);
  if (n < min || n > max) die(`${name} out of range [${min}, ${max}]: ${n}`);
  return n;
}
function boolArg(name) {
  const v = String(arg(name, "false")).toLowerCase();
  if (v !== "true" && v !== "false") die(`${name} must be 'true' or 'false', got '${arg(name)}'`);
  return v === "true";
}
function jsonArg(name, { required = true } = {}) {
  const raw = arg(name);
  if (raw === undefined) { if (required) die(`missing ${name}`); return undefined; }
  try { return JSON.parse(raw); } catch (e) { die(`${name} is not valid JSON: ${e.message}`); }
}
function readJSON(p, { required = true, label = p } = {}) {
  if (!fs.existsSync(p)) { if (required) die(`not found: ${label}`, 2); return null; }
  try { return JSON.parse(fs.readFileSync(p, "utf8")); }
  catch (e) { if (required) die(`corrupt JSON in ${label}: ${e.message}`, 2); return null; }
}
function mkdirp(p) { try { fs.mkdirSync(p, { recursive: true }); } catch (e) { die(`cannot create ${p}: ${e.message}`, 2); } }
function atomicWrite(p, data) {
  const tmp = `${p}.tmp.${process.pid}`;
  try { fs.writeFileSync(tmp, data); fs.renameSync(tmp, p); }
  catch (e) { try { fs.rmSync(tmp, { force: true }); } catch {} die(`cannot write ${p}: ${e.message}`, 2); }
}

function uroot(root) { return path.join(root, ".understanding"); }
function manifestPath(root, slug) { return path.join(uroot(root), "explainers", slug, "manifest.json"); }
function noncePath(root, slug) { return path.join(uroot(root), ".nonces", `${slug}.json`); }
function passPath(root, slug) { return path.join(uroot(root), "passes", `${slug}.json`); }
function attemptsPath(root, slug) { return path.join(uroot(root), ".work", `${slug}.attempts.json`); }

// canonical MCQ answers: {qid: "B"} sorted by qid; each value must be a single A–Z letter.
function canonicalMcq(obj) {
  if (!obj || typeof obj !== "object" || Array.isArray(obj)) die("--mcq-answers must be a JSON object {qid: LETTER}");
  const out = {};
  for (const k of Object.keys(obj).sort()) {
    const v = String(obj[k]).trim().toUpperCase();
    if (!/^[A-Z]$/.test(v)) die(`mcq answer for ${k} must be a single letter A–Z, got '${obj[k]}'`);
    out[k] = v;
  }
  if (Object.keys(out).length === 0) die("--mcq-answers is empty");
  return JSON.stringify(out);
}
// canonical free-text answers: {qid: text} sorted by qid → stable string → hashed (never stored raw).
function freeSha(obj) {
  const src = obj && typeof obj === "object" && !Array.isArray(obj) ? obj : {};
  const out = {};
  for (const k of Object.keys(src).sort()) out[k] = String(src[k]).trim();
  return sha256(JSON.stringify(out));
}
function tokenFor(rangeSha, nonces, mcqAnswers, fSha) {
  if (!rangeSha) die("missing rangeSha for token", 2);
  if (!nonces || typeof nonces !== "object") die("missing/invalid nonces for token", 2);
  const sortedNonceVals = Object.keys(nonces).sort().map((k) => nonces[k]).join(",");
  return sha256([rangeSha, sortedNonceVals, canonicalMcq(mcqAnswers), fSha].join("\n"));
}

const cmd = process.argv[2];
const root = path.resolve(arg("--root", process.cwd()));

// ---- attempt: log a pre-feedback score, return the first-attempt score --------------------------
if (cmd === "attempt") {
  const slug = assertSlug(arg("--slug"));
  const total = intArg("--total");
  const mcqCorrect = intArg("--mcq-correct", { max: total });
  const ap = attemptsPath(root, slug);
  mkdirp(path.dirname(ap));
  let attempts = readJSON(ap, { required: false, label: "attempts" });
  if (!Array.isArray(attempts)) attempts = [];
  attempts.push({ mcqCorrect, total, at: new Date().toISOString() });
  atomicWrite(ap, JSON.stringify(attempts, null, 2) + "\n");
  const first = attempts[0];
  console.log(JSON.stringify({ ok: true, attemptNumber: attempts.length, firstAttempt: { mcqCorrect: first.mcqCorrect, total: first.total } }));
  process.exit(0);
}

// ---- mint: on a genuine pass, write a pass record with an unforgeable token ---------------------
if (cmd === "mint") {
  const slug = assertSlug(arg("--slug"));
  const who = arg("--who");
  if (!who) die("mint needs --who (the person who passed)");
  const total = intArg("--total");
  const mcqCorrect = intArg("--mcq-correct", { max: total });
  const freeOk = boolArg("--free-ok");
  const mcqAnswers = jsonArg("--mcq-answers");
  const freeAnswers = jsonArg("--free-answers", { required: false }) || {};

  // guards — refuse to mint unless this is a real, complete pass
  if (total <= 0 || mcqCorrect !== total) die(`refusing to mint: MCQ not all correct (${mcqCorrect}/${total}).`);
  if (!freeOk) die("refusing to mint: free-text answer(s) not judged defensible (--free-ok true).");
  const nonceDoc = readJSON(noncePath(root, slug), { required: false, label: "nonces (gitignored)" });
  if (!nonceDoc) die(`refusing to mint: nonces for ${slug} not found (gitignored, generated at explainer build). Grade on the machine that built the explainer.`, 2);
  if (!nonceDoc.nonces) die("refusing to mint: nonce file has no nonces.", 2);
  const manifest = readJSON(manifestPath(root, slug), { label: "manifest" });
  if (!manifest.rangeSha) die("refusing to mint: manifest missing rangeSha.", 2);
  if (nonceDoc.rangeSha !== manifest.rangeSha) die("refusing to mint: nonce/manifest rangeSha mismatch (stale explainer — regenerate).");

  const fSha = freeSha(freeAnswers);
  const token = tokenFor(manifest.rangeSha, nonceDoc.nonces, mcqAnswers, fSha);

  let firstAttempt = { mcqCorrect, total };
  const attempts = readJSON(attemptsPath(root, slug), { required: false, label: "attempts" });
  if (Array.isArray(attempts) && attempts[0]) firstAttempt = { mcqCorrect: attempts[0].mcqCorrect, total: attempts[0].total };

  mkdirp(path.join(uroot(root), "passes"));
  const record = {
    slug, rangeSha: manifest.rangeSha, token, who,
    freeText: { ok: freeOk, sha: fSha },
    firstAttempt, passedAt: new Date().toISOString(),
    schema: "understanding/pass@1",
  };
  atomicWrite(passPath(root, slug), JSON.stringify(record, null, 2) + "\n");
  console.log(JSON.stringify({ ok: true, minted: true, ...record }));
  process.exit(0);
}

// ---- verify: re-derive answers -> recompute token -> authentic vs forged ------------------------
if (cmd === "verify") {
  const slug = assertSlug(arg("--slug"));
  const mcqAnswers = jsonArg("--mcq-answers");
  const rec = readJSON(passPath(root, slug), { label: "pass record" });
  if (!rec.token || !rec.rangeSha) die("pass record missing token/rangeSha.", 2);
  const nonceDoc = readJSON(noncePath(root, slug), { required: false, label: "nonces" });
  if (!nonceDoc || !nonceDoc.nonces) die(`nonces for ${slug} not present locally — cannot recompute token (verify on the build machine).`, 2);
  const fSha = (rec.freeText && rec.freeText.sha) || freeSha({}); // use the stored free-text hash
  const recomputed = tokenFor(rec.rangeSha, nonceDoc.nonces, mcqAnswers, fSha);
  const authentic = recomputed === rec.token;
  console.log(JSON.stringify({ ok: true, authentic, who: rec.who, firstAttempt: rec.firstAttempt }));
  process.exit(authentic ? 0 : 3);
}

// ---- check: fast existence + freshness (no grading). used by the pre-push hook ------------------
if (cmd === "check") {
  let slug = arg("--slug");
  let expectedRangeSha = null;
  const rangeArg = arg("--range");
  if (!slug && rangeArg) {
    const dashIdx = process.argv.indexOf("--");
    const pathspec = dashIdx >= 0 ? process.argv.slice(dashIdx) : [];
    let out;
    try { out = execFileSync("bash", [RESOLVER, rangeArg, ...pathspec], { cwd: root, encoding: "utf8" }); }
    catch (e) { die("could not resolve range: " + (e.stderr || e.message), 2); }
    let j;
    try { j = JSON.parse(out); } catch (e) { die("resolver output was not valid JSON: " + e.message, 2); }
    if (j.error) die("resolver: " + j.error, 2);
    slug = j.slug; expectedRangeSha = j.rangeSha;
  }
  assertSlug(slug);
  const pp = passPath(root, slug);
  if (!fs.existsSync(pp)) { console.log(JSON.stringify({ ok: false, reason: "no-pass", slug })); process.exit(1); }
  const rec = readJSON(pp, { label: "pass record" });
  const manifest = readJSON(manifestPath(root, slug), { required: false, label: "manifest" });
  const ref = expectedRangeSha || (manifest && manifest.rangeSha);
  if (ref && rec.rangeSha !== ref) { console.log(JSON.stringify({ ok: false, reason: "stale", slug })); process.exit(1); }
  // author != certifier (team/pr-check): the person who passed must not be the change's author.
  const certNot = arg("--certifier-not");
  if (certNot) {
    // certNot may be "Name <email>", a bare email, or a bare name (best-effort identity match).
    const emailRe = /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/i;
    const normEmail = (e) => { if (!e) return ""; const [loc, dom] = e.toLowerCase().split("@"); return loc.split("+")[0] + "@" + dom; }; // strip +tag
    const who = String(rec.who || "");
    const whoEmail = normEmail((who.match(emailRe) || [])[0]);
    const certEmail = normEmail((certNot.match(emailRe) || [])[0]);
    const certName = certNot.replace(/<[^>]*>/g, "").replace(emailRe, "").trim().toLowerCase();
    const selfCertified =
      (!!whoEmail && !!certEmail && whoEmail === certEmail) ||          // emails match (tag-normalized)
      (certName.length >= 2 && who.toLowerCase().includes(certName));  // else fall back to name
    if (selfCertified) { console.log(JSON.stringify({ ok: false, reason: "self-certified", slug, who: rec.who })); process.exit(1); }
  }
  console.log(JSON.stringify({ ok: true, slug, who: rec.who, passedAt: rec.passedAt }));
  process.exit(0);
}

die(`unknown command '${cmd || ""}'. Use: attempt | mint | verify | check`, 64);
